vars:
  - common:
      root: set PYTHONPATH=%PYTHONPATH%;./
      config: src/config.yml
stages:
  merge_data:
    cmd: python src/data/merge_data.py data/raw/ data/interim/data_test_labels.csv data/interim/data_train.csv
    deps:
      - data/raw/
      - src/data/merge_data.py
    outs:
      - data/interim/data_test_labels.csv
      - data/interim/data_train.csv
  aggregate_weather:
    cmd: ${common.root} && python src/data/aggregate_weather.py data/interim/data_train.csv data/interim/data_agg_weather.csv
    deps:
      - data/interim/data_train.csv
      - src/data/aggregate_weather.py
      - src/data/aggregate_weather_config.py
      - src/data/process_weather.py
    outs:
      - data/interim/data_agg_weather.csv
  clip_data:
    cmd: ${common.root} && python src/data/clip_outliers.py data/interim/data_agg_weather.csv data/interim/data_clipped.csv
    params:
      - ${common.config}:
        - clip_outliers
    deps:
      - data/interim/data_agg_weather.csv
      - src/data/clip_outliers.py
    outs:
      - data/interim/data_clipped.csv
  create_features:
    cmd: ${common.root} && python src/features/create_features.py data/interim/data_clipped.csv data/processed/data_featured.csv
    deps:
      - data/interim/data_clipped.csv
      - src/features/create_features.py
      - src/features/create_features_config.py
      - src/features/math_functions.py
      - src/features/process_features.py
    outs:
      - data/processed/data_featured.csv
  plot_exploratory:
    cmd: ${common.root} && python src/visualization/plot_exploratory.py data/processed/data_featured.csv reports/figures/exploratory/
    params:
      - ${common.config}:
        - plot_exploratory
    deps:
      - data/processed/data_featured.csv
      - src/visualization/plot_exploratory.py 
    outs:
      - reports/figures/exploratory/:
          persist: True
          cache: False
  plot_feature_importances:
    cmd: ${common.root} && python src/visualization/plot_feature_importance.py data/processed/data_featured.csv reports/figures/importance/
    params:
      - ${common.config}:
        - plot_feature_importance
    deps:
      - data/processed/data_featured.csv
      - src/visualization/plot_feature_importance.py 
    outs:
      - reports/figures/importance/:
          persist: True
          cache: False
