vars:
  - common:
      root: "./" 
stages:
  merge_data:
    cmd: python src/data/merge_data.py data/raw/ data/interim/data_test_labels.csv data/interim/data_train.csv
    deps:
      - data/raw/
      - src/data/merge_data.py
    outs:
      - data/interim/data_test_labels.csv
      - data/interim/data_train.csv
  aggregate_weather:
    cmd: python src/data/aggregate_weather.py data/interim/data_train.csv data/interim/data_agg_weather.csv
    deps:
      - data/interim/data_train.csv
      - src/data/aggregate_weather.py
      - src/data/aggregate_weather_config.py
      - src/data/process_weather.py
    outs:
      - data/interim/data_agg_weather.csv
  clip_data:
    cmd: python src/data/clip_outliers.py data/interim/data_agg_weather.csv data/interim/data_clipped.csv
    deps:
      - data/interim/data_agg_weather.csv
      - src/data/clip_outliers.py
    outs:
      - data/interim/data_clipped.csv
  create_features:
    cmd: set PYTHONPATH=%PYTHONPATH%;${common.root} && python src/features/create_features.py data/interim/data_clipped.csv data/interim/data_featured.csv
    deps:
      - data/interim/data_clipped.csv
      - src/features/create_features.py
      - src/features/create_features_config.py
      - src/features/math_functions.py
      - src/features/process_features.py
    outs:
      - data/interim/data_featured.csv
