[tool.pylint.format]
max-line-length = 88
variable-rgx = "[a-z_][a-z0-9_]{1,30}$"
disable = ["C0303", "C0103"]
signature-mutators = ["click.decorators.argument"]

[tool.black]
target-version = ['py310']
line-length = 88
