common:
  seed: 42
  target: wp
  date_col: date

clip_outliers:
  clip_strategy: quantile_clip
  quantile_clip:
    exclude: [date, hors, hour, wd, month, wp, windfarm]
    lower: 0.05
    upper: 0.95
  iqr_clip:
    exclude: [date, hors, hour, wd, wp, windfarm]
split_train_predict:
  train_rows:
    dates: ['2009-07-02 13:00:00', '2012-06-25 00:00:00']
    is_na: False
  predict_rows:
    dates: ['2011-01-01 01:00:00', '2012-06-25 00:00:00' ]
    is_na: True
plot_exploratory:
  features:
    include: [windfarm, hour, ws, wd_sin, wd_cos, side, ws-wd_cos, ws_frac, ws_log, ws_med24, ws_l3, ws_l12] # all
    exclude: []
  set_plot_params:
    is_on: True
  plot_corr_matrix:
    is_on: True
    cat_col: windfarm
    figsize: [30, 15]
    fontsize: 14
  plot_boxplot:
    is_on: True
    is_standardized: True
  plot_pairplot:
    is_on: False
    hue_col: windfarm
    kind: reg
    diag_kind: kde
    alpha: 0.3
plot_feature_importance:
  features:
    include: all
    exclude: [date]
  windfarm_col: windfarm
  get_permutation_importance:
    is_on: True
    n_repeats: 10
    train_test_cfg:
      test_size: 0.25
      shuffle: True
    random_forest_cfg:
      min_samples_leaf: 10
  plot_power_prediciton:
    is_on: True
    whiskers_len: 10
  plot_params:
    set_plot_params: True
    figsize: [30, 15]
    fontsize:
explore_train_model:
  features:
    date_period: ['2009-07-02 13:00:00', '2012-06-25 00:00:00']
    include: all # all or [...]
    exclude: [date, wd_cos_d2s1, wd_sin_d2s1, ws_d2s1, wd_sin_d2s3, wd_cos_d2s3, ws_d2s3]
  set_plot_params:
    is_on: True
  linear_model:
   cat_cols: [windfarm]
   model_params:
    regressor__feature_selector__threshold: "1.0*median"
    regressor__feature_selector__estimator__min_samples_leaf: 30
    regressor__model__fit_intercept: True
    regressor__model__alpha: 30
  params_search:
    is_on: True
    n_jobs: 4
    grid_params:
      n_splits: 5
      scoring: neg_mean_absolute_error
      regressor__model__alpha:
        - vals
        - [0.01] # np.logspace(-3, 3, num=25)
      regressor__feature_selector__threshold:
        - vals
        - ["0.4*median"] #"0.6*median", "0.8*median", "1.0*median", "1.1*median"]
    cv_params:
      n_splits: 5
      return_train_score: True
      scoring:
        MSE: neg_mean_squared_error
        MAE: neg_mean_absolute_error
    plot_param_search:
      scoring: "test_MAE"
      metrics_to_track:
        test: [MSE, MAE, MAE_median, MAE_std, MAE_eval]
      x_axis: regressor__model__alpha
      hover_cols: [test_MAE] # +grid_params
      figsize: [20, 10]
  plot_learning_curve:
    is_on: True
    n_jobs: 4
    scoring: neg_mean_absolute_error
    figsize: [20, 10]
    n_splits: 10
  mlflow_config:
    mlflow_description: "Test TransformedTargetRegressor"
    mlflow_tags:
      model: Ridge
      selector: ExtraTreesRegressor
      windfarm: categorical
    experiment_name: selector-ridge_model
